version: 2.1

executors:
  android:
    machine:
      image: android:202102-01

jobs:
  yarn-fun:
    executor: android
    environment:
      CACHE_VERSION: v1
    steps:
      - run:
          name: install Yarn globally
          command: npm install --global yarn
      - run:
          name: quick diagnose
          command: |
            which yarn && yarn --version
      - checkout
      - run:
          name: install some modules
          command: |
            yarn install
            cat yarn.lock
            # find out total size
            du -sh node_modules
      - save_cache:
          name: Yarn - Cache update
          paths:
            - ./node_modules
          # try rm newline!
          key: yarn-cache-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ checksum "yarn.lock" }}
workflows:
  ball:
    jobs:
      - yarn-fun
